api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

log:
  level: DEBUG

providers:
  file:
    watch: true
    filename: "/local/dynamic.yml"
  consulCatalog:
    endpoint:
      scheme: http
      address: http://10.0.0.1:8500
    prefix: traefik
    exposedByDefault: false

accessLog: {}