- name: My first play
  hosts: main
  remote_user: root
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Prerequisites
      ansible.builtin.package:
        name:
        - zip
        state: present

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

#    - name: Print the package facts
#      ansible.builtin.debug:
#        var: ansible_facts.packages

    # sudo apt-get update && \
#  sudo apt-get install wget gpg coreutils
    - name: App Setup DNF
      ansible.builtin.import_tasks: app-setup-dnf.yaml
      when: ansible_distribution == 'Fedora' and 'nomad' not in ansible_facts.packages

    - name: App Setup APT
      ansible.builtin.import_tasks: app-setup-apt.yaml
      when: ansible_distribution == 'Debian' and 'nomad' not in ansible_facts.packages

    - name: NFS Configs
      ansible.builtin.import_tasks: nfs-setup.yaml
      when: ansible_hostname == "rastaman"
      
    - name: Kernel Tunings
      ansible.builtin.import_tasks: kernel-tunings.yaml

    - name: App Configs
      ansible.builtin.import_tasks: app-confs.yaml

    - name: CNI Config
      ansible.builtin.import_tasks: cni-config.yaml

    - name: Services
      ansible.builtin.import_tasks: services.yaml