---
- name: Restart Docker
  ansible.builtin.systemd_service:
    state: restarted
    name: docker

- name: Restart Nomad
  ansible.builtin.systemd_service:
    state: restarted
    name: nomad

- name: Restart Consul
  ansible.builtin.systemd_service:
    state: restarted
    name: consul
    no_block: true
