---
#- name: Restart Docker
#  ansible.builtin.systemd_service:
#    state: restarted
#    name: docker

- name: Reload Nomad
  ansible.builtin.systemd_service:
    state: reloaded
    name: nomad

- name: Reload Consul
  ansible.builtin.systemd_service:
    state: restarted
    name: consul
    no_block: true
