---
#- name: Restart Docker
#  ansible.builtin.systemd_service:
#    state: restarted
#    name: docker

- name: Enable Docker Service
  ansible.builtin.systemd_service:
    state: started
    name: docker
    enabled: true

- name: Reload Nomad
  ansible.builtin.systemd_service:
    state: reloaded
    name: nomad
    enabled: true

- name: Reload Consul
  ansible.builtin.systemd_service:
    state: restarted
    name: consul
    no_block: true
    enabled: true
